"""
Writes tests/conformance/golden/pyca-*.json: DPoP proofs signed by
python-cryptography, with the RFC 7638 thumbprint computed here from the
JWK's required members, so neither the signature nor the thumbprint comes
from jose or from Antlion.

    python3 tools/golden/pyca_dpop.py

Each run makes new keys; the tests only need each file to be internally
consistent.
"""

import base64
import hashlib
import json
import pathlib

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec, ed25519, padding, rsa
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature

OUT = pathlib.Path(__file__).resolve().parents[2] / "tests" / "conformance" / "golden"
TOKEN = "eyJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJweWNhIn0.c2lnbmF0dXJl"
HTU = "https://api.example.com/accounts/42"
IAT = 1790000000


def b64(data: bytes) -> str:
	return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def uint(value: int, length: int | None = None) -> str:
	length = length or (value.bit_length() + 7) // 8
	return b64(value.to_bytes(length, "big"))


def thumbprint(jwk: dict, members: list[str]) -> str:
	canonical = json.dumps({m: jwk[m] for m in sorted(members)}, separators=(",", ":"))
	return b64(hashlib.sha256(canonical.encode()).digest())


def write(name: str, alg: str, jwk: dict, members: list[str], sign) -> None:
	header = {"typ": "dpop+jwt", "alg": alg, "jwk": jwk}
	payload = {
		"jti": f"pyca-{name}",
		"htm": "POST",
		"htu": HTU,
		"iat": IAT,
		"ath": b64(hashlib.sha256(TOKEN.encode()).digest()),
	}
	signing_input = f"{b64(json.dumps(header).encode())}.{b64(json.dumps(payload).encode())}"
	proof = f"{signing_input}.{b64(sign(signing_input.encode()))}"
	fixture = {
		"$comment": "Generated by tools/golden/pyca_dpop.py with python-cryptography.",
		"proof": proof,
		"method": "POST",
		"htu": HTU,
		"token": TOKEN,
		"nowMs": IAT * 1000,
		"jkt": thumbprint(jwk, members),
	}
	(OUT / f"pyca-{name}.json").write_text(json.dumps(fixture, indent="\t") + "\n")


def main() -> None:
	p256 = ec.generate_private_key(ec.SECP256R1())
	numbers = p256.public_key().public_numbers()
	ec_jwk = {"kty": "EC", "crv": "P-256", "x": uint(numbers.x, 32), "y": uint(numbers.y, 32)}

	def es256(data: bytes) -> bytes:
		r, s = decode_dss_signature(p256.sign(data, ec.ECDSA(hashes.SHA256())))
		return r.to_bytes(32, "big") + s.to_bytes(32, "big")

	write("es256", "ES256", ec_jwk, ["crv", "kty", "x", "y"], es256)

	ed = ed25519.Ed25519PrivateKey.generate()
	raw = ed.public_key().public_bytes_raw()
	ed_jwk = {"kty": "OKP", "crv": "Ed25519", "x": b64(raw)}
	write("ed25519", "Ed25519", ed_jwk, ["crv", "kty", "x"], ed.sign)
	write("eddsa", "EdDSA", ed_jwk, ["crv", "kty", "x"], ed.sign)

	rsa_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
	rsa_numbers = rsa_key.public_key().public_numbers()
	rsa_jwk = {"kty": "RSA", "n": uint(rsa_numbers.n), "e": uint(rsa_numbers.e)}

	def ps256(data: bytes) -> bytes:
		return rsa_key.sign(data, padding.PSS(padding.MGF1(hashes.SHA256()), 32), hashes.SHA256())

	write("ps256", "PS256", rsa_jwk, ["e", "kty", "n"], ps256)


if __name__ == "__main__":
	main()
