/*
 * Writes tests/conformance/golden/nimbus-*.json: DPoP proofs made by Nimbus
 * OAuth 2.0 SDK's DefaultDPoPProofFactory, with the RFC 7638 thumbprint
 * computed by Nimbus. The Java side of the golden vectors, next to
 * tools/golden/pyca_dpop.py.
 *
 *     cd tools/golden/nimbus
 *     mvn -q dependency:copy-dependencies -DoutputDirectory=lib
 *     java -cp "lib/*" NimbusDPoP.java
 *
 * Each run makes new keys; the tests only need each file to be internally
 * consistent. lib/ is not committed.
 */

import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.jwk.Curve;
import com.nimbusds.jose.jwk.JWK;
import com.nimbusds.jose.jwk.gen.ECKeyGenerator;
import com.nimbusds.jose.jwk.gen.OctetKeyPairGenerator;
import com.nimbusds.jose.jwk.gen.RSAKeyGenerator;
import com.nimbusds.oauth2.sdk.dpop.DefaultDPoPProofFactory;
import com.nimbusds.oauth2.sdk.id.JWTID;
import com.nimbusds.oauth2.sdk.token.DPoPAccessToken;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Date;

public class NimbusDPoP {
	static final Path OUT = Path.of("..", "..", "..", "tests", "conformance", "golden");
	static final String TOKEN = "eyJhbGciOiJFUzI1NiJ9.eyJzdWIiOiJuaW1idXMifQ.c2lnbmF0dXJl";
	static final String HTU = "https://api.example.com/accounts/42";
	static final long IAT = 1790000000L;

	public static void main(String[] args) throws Exception {
		write("es256", new ECKeyGenerator(Curve.P_256).generate(), JWSAlgorithm.ES256);
		write("ps256", new RSAKeyGenerator(2048).generate(), JWSAlgorithm.PS256);
		JWK ed = new OctetKeyPairGenerator(Curve.Ed25519).generate();
		write("eddsa", ed, JWSAlgorithm.EdDSA);
		write("ed25519", ed, JWSAlgorithm.Ed25519);
	}

	static void write(String name, JWK key, JWSAlgorithm alg) throws Exception {
		var factory = new DefaultDPoPProofFactory(key, alg);
		var proof = factory.createDPoPJWT(
			new JWTID("nimbus-" + name), "POST", URI.create(HTU), new Date(IAT * 1000), new DPoPAccessToken(TOKEN));
		var json = "{\n"
			+ "\t\"$comment\": \"Generated by tools/golden/nimbus/NimbusDPoP.java with Nimbus OAuth 2.0 SDK.\",\n"
			+ "\t\"proof\": \"" + proof.serialize() + "\",\n"
			+ "\t\"method\": \"POST\",\n"
			+ "\t\"htu\": \"" + HTU + "\",\n"
			+ "\t\"token\": \"" + TOKEN + "\",\n"
			+ "\t\"nowMs\": " + (IAT * 1000) + ",\n"
			+ "\t\"jkt\": \"" + key.toPublicJWK().computeThumbprint() + "\"\n"
			+ "}\n";
		Files.writeString(OUT.resolve("nimbus-" + name + ".json"), json);
	}
}
